name: PHP Composer

on:
  push:
    branches: [ "aprendiendo-github-actions" ]
  pull_request:
    branches: [ "aprendiendo-github-actions" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Exec file
      run: php index.php

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
